const { PORT, DRUGBANK, DRUGBANKDOCS, DRUGBANKSERVICES, DRUGBANKSORTPARAMETER, PORTDRUGBANK, USERAGENT, ACCEPT, COLLECTION, TOKENCRAWLER } = process.env;

const COLLECTION_DEFAULT = COLLECTION ? COLLECTION : 'drugbank';

export {
    PORT, DRUGBANK, DRUGBANKDOCS, DRUGBANKSERVICES, DRUGBANKSORTPARAMETER, PORTDRUGBANK, USERAGENT, ACCEPT, COLLECTION_DEFAULT, TOKENCRAWLER
}