const { PORT, DRUGBANK, DRUGBANKDOCS, DRUGBANKSERVICES, DRUGBANKSORTPARAMETER, PORTDRUGBANK, USERAGENT, ACCEPT, COLLECTION, TOKENCRAWLER } = process.env;

export {
    PORT, DRUGBANK, DRUGBANKDOCS, DRUGBANKSERVICES, DRUGBANKSORTPARAMETER, PORTDRUGBANK, USERAGENT, ACCEPT, COLLECTION, TOKENCRAWLER
}